### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by vanstr** [vanstr/cp-web#12]
User profile page
- delete account
- ? adding password for users authorized through Cloud services (Dropbox,GDrive)
- password changing

Password encryption in DB

Displaying correct user information in CloudPlayer UI

**Comment by vanstr** [comment]
zamutil cascad. Validator v popu, universaljnim ne polu4itsja sdelatj, tam errori nado budet kakto obrabativatj

**Comment by alex-vo** [comment]
Всё хорошо сделал. Единственно остаётся открытый вопрос о валидаторе. А так можешь мерджить в мастер.
